### ISSUE TITLE
For Spicetify?

### ISSUE THREAD

**Issue by FiftyFour7250** [jakubkastner/released-albums#1]
Hey. I know it's outside of your project, but maybe you'd be interested? Do you know about [Spicetify](https://github.com/khanhas/spicetify-cli)? This is tool for modifying the appearance and capabilities of Spotify. [It also has New Releases](https://github.com/khanhas/spicetify-cli/wiki/Extensions#new-release), but unlike your site, it doesn't show Appearances,  only Albums and Singles, which is why a lot of songs are skipped. I [asked](https://github.com/khanhas/spicetify-cli/issues/450) author to add Appearances, but he thinks that they will be superfluous, although he said that he can help. Maybe you want to make your own version of the extension for Spicetify? I'm not programmer, but your site and its extension on javascript, so maybe it's not that hard...

**Comment by jakubkastner** [comment]
Hi, thanks for suggestion. I didn't know about Spicetify until now and it looks like a useful addon to Spotify.
At the moment I don't have enough time to focus on this integration, because I am working on a remake and redesign my application. However I could prepare it for future integration with Spicetify.

Currently, integration with Spicetify has no priority, however, integration is possible in the future.
